name: councilwatch

services:
  client:
    build:
      context: .
      dockerfile: client.Dockerfile
    ports:
      - 8080:8080
    networks:
      - frontend

  server:
    build:
      context: .
      dockerfile: server.Dockerfile
    environment:
      - DATABASE_URL=postgres://postgres:postgres@database:5432/councilwatch
    networks:
      - backend
      - frontend

  database:
    image: "postgres:18"
    environment:
      - POSTGRES_DB=councilwatch
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - councilwatch_data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  councilwatch_data:

networks:
  # Network isolation so, for example, the frontend cannot access the database
  backend:
  frontend:
