services:
  councilwatch-server:
    build:
      context: .
      dockerfile: server.Dockerfile
    environment:
      - DATABASE_URL=postgres://postgres:postgres@database:5432/councilwatch
    networks:
      - backend
      - frontend


  councilwatch-client:
    build:
      context: .
      dockerfile: client.Dockerfile
    ports:
      - 5173:5173
    networks:
      - frontend

  database:
    image: "postgres:18"
    environment:
      - POSTGRES_DB=councilwatch
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - councilwatch_data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  councilwatch_data:

networks:
  backend:
  frontend:
