services:
  councilwatch-server:
    build: .
    environment:
      - DATABASE_URL=postgres://postgres:postgres@database:5432/councilwatch
    networks:
      - backend
      - frontend
    command: ["start:server"]


  councilwatch-client:
    build: .
    ports:
      - 5173:5173
    networks:
      - frontend
    command: ["start:client"]

  database:
    image: "postgres:18"
    environment:
      - POSTGRES_DB=councilwatch
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - councilwatch_data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  councilwatch_data:

networks:
  backend:
  frontend:
