#!/usr/bin/env node

const fs = require('fs');
const fsp = require('fs/promises');
const path = require('path');
const https = require('https');
const { pipeline } = require('stream/promises');
const { spawn } = require('child_process');

const YEAR = 2024;
const BASE = `https://www2.census.gov/geo/docs/maps-data/data/gazetteer/${YEAR}_Gazetteer`;
const DATA_DIR = path.join(__dirname, 'sample_council_data');
const OUTPUT_MODES = { SQL: 'sql', CSV: 'csv' };

const LAYERS = [
  { key: 'counties', label: 'county', predicate: () => true },
  { key: 'place', label: 'place', predicate: (row) => row.FUNCSTAT === 'A' },
  {
    key: 'cousubs',
    label: 'county subdivision',
    predicate: (row) => ['A', 'B', 'C', 'G'].includes(row.FUNCSTAT),
  },
];

function log(message) {
  console.error(message);
}

async function fetchToFile(url, dest) {
  await fsp.mkdir(path.dirname(dest), { recursive: true });
  return new Promise((resolve, reject) => {
    https
      .get(url, (res) => {
        if (res.statusCode !== 200) {
          reject(new Error(`HTTP ${res.statusCode} for ${url}`));
          res.resume();
          return;
        }
        pipeline(res, fs.createWriteStream(dest)).then(resolve).catch(reject);
      })
      .on('error', reject);
  });
}

async function unzip(zipPath, outDir) {
  await fsp.mkdir(outDir, { recursive: true });
  return new Promise((resolve, reject) => {
    const proc = spawn('unzip', ['-o', zipPath, '-d', outDir], { stdio: 'ignore' });
    proc.on('close', (code) => (code === 0 ? resolve() : reject(new Error(`unzip exited ${code}`))));
    proc.on('error', reject);
  });
}

function parseTsv(filePath) {
  const contents = fs.readFileSync(filePath, 'utf8');
  const lines = contents.split(/\r?\n/).filter(Boolean);
  const headers = lines.shift().split('\t').map((h) => h.trim());
  return lines.map((line) => {
    const cells = line.split('\t');
    return headers.reduce((acc, key, idx) => {
      acc[key] = (cells[idx] || '').trim();
      return acc;
    }, {});
  });
}

async function fileExists(filePath) {
  try {
    await fsp.access(filePath);
    return true;
  } catch {
    return false;
  }
}

async function collectCouncilRows() {
  await fsp.mkdir(DATA_DIR, { recursive: true });
  const rows = [];

  for (const layer of LAYERS) {
    const url = `${BASE}/${YEAR}_Gaz_${layer.key}_national.zip`;
    const zipPath = path.join(DATA_DIR, `${YEAR}_Gaz_${layer.key}_national.zip`);
    const txtPath = path.join(DATA_DIR, `${YEAR}_Gaz_${layer.key}_national.txt`);

    const hasTxt = await fileExists(txtPath);
    if (!hasTxt) {
      log(`-> Downloading ${layer.key} from ${url}`);
      await fetchToFile(url, zipPath);
      await unzip(zipPath, DATA_DIR);
    } else {
      log(`-> Using cached ${txtPath}`);
    }

    const parsed = parseTsv(txtPath);
    const filtered = parsed
      .filter(layer.predicate)
      .filter((row) => row.NAME && row.INTPTLAT && row.INTPTLONG)
      .map((row) => ({
        name: `${row.NAME} (${layer.label})`,
        lat: Number(row.INTPTLAT),
        lon: Number(row.INTPTLONG),
      }));

    log(`   Kept ${filtered.length} out of ${parsed.length} rows after filtering (${parsed.length - filtered.length} discarded)`);
    rows.push(...filtered);
  }

  if (rows.length === 0) {
    throw new Error('No council rows were discovered.');
  }

  return rows;
}

function rowsToSql(rows) {
  const inserts = rows.map((row, index) => {
    const id = index + 1;
    const name = `'${row.name.replace(/'/g, "''")}'`;
    if (Number.isNaN(row.lat) || Number.isNaN(row.lon)) {
      throw new Error(`Invalid coordinates for row ${row.name}`);
    }
    return `(${id}, ${name}, ${row.lat}, ${row.lon})`;
  });

  return [
    '-- Auto-generated by scripts/seed_sample_council_data.cjs',
    'BEGIN;',
    'DELETE FROM councils;',
    'INSERT INTO councils (id, name, lat, lon) VALUES',
    `${inserts.join(',\n')};`,
    "SELECT setval('councils_id_seq', (SELECT COALESCE(MAX(id), 1) FROM councils));",
    'COMMIT;',
    '',
  ].join('\n');
}

function rowsToCsv(rows) {
  const lines = ['name,lat,lon'];
  for (const row of rows) {
    lines.push(`${row.name},${row.lat},${row.lon}`);
  }
  return lines.join('\n') + '\n';
}

function printHelp() {
  const helpText = `Usage: node scripts/seed_sample_council_data.cjs [--csv]\n\n` +
    `Downloads the US Census gazetteer data, filters supported councils, and emits SQL (default) or CSV to stdout.\n` +
    `  --csv   Output CSV instead of SQL (useful for inspection)\n` +
    `  --help  Show this message`;
  console.log(helpText);
}

function parseArgs() {
  const args = process.argv.slice(2);
  const options = { mode: OUTPUT_MODES.SQL, help: false };

  for (const arg of args) {
    if (arg === '--help' || arg === '-h') {
      options.help = true;
    } else if (arg === '--csv') {
      options.mode = OUTPUT_MODES.CSV;
    } else {
      throw new Error(`Unknown argument: ${arg}`);
    }
  }

  return options;
}

process.stdout.on('error', (err) => {
  if (err.code === 'EPIPE') {
    process.exit(0);
  } else {
    throw err;
  }
});

async function main() {
  const options = parseArgs();
  if (options.help) {
    printHelp();
    return;
  }

  const rows = await collectCouncilRows();
  const output = options.mode === OUTPUT_MODES.CSV ? rowsToCsv(rows) : rowsToSql(rows);
  process.stdout.write(output);
}

main().catch((err) => {
  console.error(err.message);
  process.exitCode = 1;
});
